### PR TITLE
Add LogChimp product in product management section

### PR DESCRIPTION
**Pull request by mittalyashu**

### CODE REVIEW

**Comment by ishanvyas22** [comment]
I doesn't look like LogChimp falls into Project management category. Can you please identify correct category and add into that?

**Comment by mittalyashu** [comment]
@ishanvyas22 LogChimp is a project management software as in,

> LogChimp helps product managers by accepting customers feedback and based on that prioritise what's next to build and drive the team members according to the roadmap.

**Comment by ishanvyas22** [comment]
Fair enough. But you have to add it after Goodwork as all the list are sorted alphabetically.

**Comment by mittalyashu** [comment]
@ishanvyas22 Can you review the changes?

**Comment by mittalyashu** [comment]
Thanks

**Pull request merged**
